module.exports = {
  NOTIFICATION_TYPE: {
    PICKUP_CREATED: "PICKUP_CREATED",
    PICKUP_ASSIGNED: "PICKUP_ASSIGNED",
    PICKUP_ACCEPTED: "PICKUP_ACCEPTED",
    PICKUP_IN_PROGRESS: "PICKUP_IN_PROGRESS",
    PICKUP_COMPLETED: "PICKUP_COMPLETED",
    PICKUP_CANCELLED: "PICKUP_CANCELLED",
    WALLET_CREDITED: "WALLET_CREDITED",
    WALLET_DEBITED: "WALLET_DEBITED",
  },

  NOTIFICATION_CHANNEL: {
    IN_APP: "IN_APP",
    SMS: "SMS",
    EMAIL: "EMAIL",
    PUSH: "PUSH",
  },

  NOTIFICATION_USER_TYPE: {
    ADMIN: "ADMIN",
    USER: "USER",
    SCRAP_COLLECTOR: "SCRAP_COLLECTOR",
  },
};
